"""Ajout de la colonne genome dans la colonne application pour sauvegarder le genome d'un job_seeker qui a postuler a une offre

Revision ID: 05b9f25e8749
Revises: 4eb2c9e4fa5f
Create Date: 2025-04-10 13:11:10.968239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b9f25e8749'
down_revision = '4eb2c9e4fa5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genome', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('genome')

    # ### end Alembic commands ###
