"""Ajout de la colonne de date de creation sur toutes les tables

Revision ID: 4eb2c9e4fa5f
Revises: 91bee0c26472
Create Date: 2025-04-10 12:08:04.917099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb2c9e4fa5f'
down_revision = '91bee0c26472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_seeker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_seeker', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
