"""Changement de la nature de la colonne de genome

Revision ID: 95d56447dba1
Revises: 05b9f25e8749
Create Date: 2025-04-28 06:01:42.341089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95d56447dba1'
down_revision = '05b9f25e8749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column(
            'genome',
            existing_type=postgresql.BYTEA(),
            type_=postgresql.JSON(astext_type=sa.Text()),
            existing_nullable=True,
            postgresql_using="NULL"  # <<<<<< ON FORCE À NULL pour éviter erreur
        )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('genome',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
